CREATE TABLE "public"."rental" (
    "id" int4 NOT NULL,
    "site" text,
    "title" text,
    "url" text,
    "image" text,
    "warmmiete" text,
    "kaltmiete" text,
    "nebenkosten" text,
    "heizungskosten" text,
    "kaution" text,
    "area" text,
    "num_rooms" text,
    "address" text,
    "postcode" text,
    "geo_latitude" text,
    "geo_longitude" text,
    "offer_id" text NOT NULL,
    "balcony" text,
    "energy_building_year" text,
    "kitchen_availability" text,
    "cellar" text,
    "pets_allowed" text,
    "energy_efficiency_class" text,
    "energy_consumption" text,
    "elevator" text,
    "floor_level" text,
    "garden" text,
    "handicap_accessible" text,
    "freetext_property_description" text,
    "freetext_area_description" text,
    "freetext_other" text,
    "heating" text,
    "preis_qm_kalt" text,
    "available_from_date" text
);
